app/account/urls.py
from django.urls import path

from account.views import (
    UserSignUpView,
    UserActivateView,
)

app_name = 'account'

urlpatterns = [
    path('signup/', UserSignUpView.as_view(), name='signup'),
    path('activate/<uuid:username>/', UserActivateView.as_view(), name='activate')
]

app/currency/api/urls.py
from currency.api.views import RateViewSet, ContactUsViewSet, SourceViewSet
from rest_framework.routers import DefaultRouter


router = DefaultRouter()
router.register('rates', RateViewSet, basename='rates')
router.register('contactus', ContactUsViewSet, basename='contactus')
router.register('sources', SourceViewSet, basename='sources')

app_name = 'api-currency'

urlpatterns = []

urlpatterns += router.urls

app/currency/urls.py
from django.urls import path

from currency.views import (
    RateListView, RateDetailsView, RateCreateView, RateUpdateView, RateDeleteView,
    ContactUsListView, ContactUsDetailsView, ContactUsCreateView, ContactUsUpdateView, ContactUsDeleteView,
    SourceListView, SourceDetailsView, SourceCreateView, SourceUpdateView, SourceDeleteView,
)

rate_patterns = [
    path('rates/list/', RateListView.as_view(), name='rate-list'),
    path('rates/<int:pk>/', RateDetailsView.as_view(), name='rate-details'),
    path('rates/create/', RateCreateView.as_view(), name='rate-create'),
    path('rates/<int:pk>/update/', RateUpdateView.as_view(), name='rate-update'),
    path('rates/<int:pk>/delete/', RateDeleteView.as_view(), name='rate-delete'),
]

contact_us_patterns = [
    path('contactus/list/', ContactUsListView.as_view(), name='contactus-list'),
    path('contactus/<int:pk>/', ContactUsDetailsView.as_view(), name='contactus-details'),
    path('contactus/create/', ContactUsCreateView.as_view(), name='contactus-create'),
    path('contactus/<int:pk>/update/', ContactUsUpdateView.as_view(), name='contactus-update'),
    path('contactus/<int:pk>/delete/', ContactUsDeleteView.as_view(), name='contactus-delete'),
]

source_patterns = [
    path('sources/list/', SourceListView.as_view(), name='source-list'),
    path('sources/<int:pk>/', SourceDetailsView.as_view(), name='source-details'),
    path('sources/create/', SourceCreateView.as_view(), name='source-create'),
    path('sources/<int:pk>/update/', SourceUpdateView.as_view(), name='source-update'),
    path('sources/<int:pk>/delete/', SourceDeleteView.as_view(), name='source-delete'),
]


app_name = 'currency'

urlpatterns = [
    *rate_patterns,
    *contact_us_patterns,
    *source_patterns,
]

app/settings/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

from currency.views import ProfileView

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)


urlpatterns = [
    path('admin/', admin.site.urls),

    path('auth/', include('django.contrib.auth.urls')),
    path('profile/', ProfileView.as_view(), name='profile'),

    path('account/', include('account.urls')),
    path('api/', include('account.api.urls')),

    path('__debug__/', include('debug_toolbar.urls')),

    path('currency/', include('currency.urls')),
    path('api/currency/', include('currency.api.urls')),

    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/account/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):

    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=20, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

app/currency/models.py
from currency import choices as mch
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.templatetags.static import static


class Rate(models.Model):

    created = models.DateTimeField(auto_now_add=True)
    currency = models.PositiveSmallIntegerField(
        choices=mch.RateCurrencyChoices.choices,
        default=mch.RateCurrencyChoices.EUR
    )
    buy = models.DecimalField(max_digits=8, decimal_places=2)
    sale = models.DecimalField(max_digits=8, decimal_places=2)
    source = models.ForeignKey('currency.Source', on_delete=models.CASCADE, related_name='rates')

    def __str__(self):
        return f'Source {{{self.source}}} on {self.created} for {self.get_currency_display()}'


class ContactUs(models.Model):

    email_from = models.EmailField()
    subject = models.CharField(max_length=100)
    message = models.TextField()

    def __str__(self):
        return f'From user {{{self.email_from}}} about "{self.subject}"'


def source_logo_path(instance, filename):
    return f"currency/sources/{instance.id}/logos/{filename}"


class Source(models.Model):

    source_url = models.URLField(max_length=255)
    name = models.CharField(max_length=64)
    code_name = models.CharField(max_length=64, unique=True)
    phone_number = PhoneNumberField(blank=True)
    contact_email = models.EmailField(blank=True)
    logo = models.FileField(
        default='',
        null=True,
        blank=True,
        upload_to=source_logo_path
    )

    def __str__(self):
        return f'{self.name}'

    @property
    def logo_url(self):
        if self.logo:
            return self.logo.url
        return static('nologo.jpg')


class RequestResponseLog(models.Model):

    path = models.CharField(max_length=150)
    request_method = models.PositiveSmallIntegerField(
        choices=mch.RateRequestResponseLogChoices.choices,
        default=mch.RateRequestResponseLogChoices.GET
    )
    time = models.PositiveIntegerField()

app/currency/forms.py
from django import forms

from currency.models import Rate, ContactUs, Source


class RateForm(forms.ModelForm):

    class Meta:
        model = Rate
        fields = (
            'buy',
            'sale',
            'source',
            'currency'
        )


class ContactUsForm(forms.ModelForm):

    class Meta:
        model = ContactUs
        fields = (
            'email_from',
            'subject',
            'message',
        )


class SourceForm(forms.ModelForm):

    class Meta:
        model = Source
        fields = (
            'source_url',
            'name',
            'phone_number',
            'contact_email',
            'logo'
        )

app/currency/api/views.py
from rest_framework import viewsets

from currency.models import Rate, Source, ContactUs
from currency.api.serializers import RateSerializer, SourceSerializer, ContactUsSerializer
from currency.api.paginators import TenThousandPagination
from currency.filters import RateFilter, ContactUsFilter

from django_filters import rest_framework as filters
from rest_framework import filters as rest_framework_filters


class SourceViewSet(viewsets.ModelViewSet):
    queryset = Source.objects.all()
    serializer_class = SourceSerializer
    pagination_class = TenThousandPagination


class RateViewSet(viewsets.ModelViewSet):
    queryset = Rate.objects.all()
    serializer_class = RateSerializer
    pagination_class = TenThousandPagination
    filter_backends = (
        filters.DjangoFilterBackend,
        rest_framework_filters.OrderingFilter,
    )
    filterset_class = RateFilter
    ordering_fields = (
        'id',
        'buy',
        'sale',
        'source',
    )


class ContactUsViewSet(viewsets.ModelViewSet):
    queryset = ContactUs.objects.all()
    serializer_class = ContactUsSerializer
    pagination_class = TenThousandPagination
    filter_backends = (
        filters.DjangoFilterBackend,
        rest_framework_filters.OrderingFilter,
        rest_framework_filters.SearchFilter,
    )
    filterset_class = ContactUsFilter
    ordering_fields = (
        'id',
        'subject',
    )
    search_fields = ['subject', 'message']

app/currency/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.conf import settings
from django_filters.views import FilterView

from currency.mixins import ModifiedPagesMixin
from currency.models import Rate, ContactUs, Source
from currency.forms import RateForm, ContactUsForm, SourceForm
from currency.tasks import send_mail
from currency.filters import RateFilter, SourceFilter, ContactUsFilter


class RateListView(ModifiedPagesMixin, FilterView):
    paginate_by = 10
    queryset = Rate.objects.all().select_related('source')
    template_name = 'models/rate/list.html'

    filterset_class = RateFilter


class RateDetailsView(LoginRequiredMixin, DetailView):
    queryset = Rate.objects.all()
    template_name = 'models/rate/details.html'


class RateCreateView(UserPassesTestMixin, CreateView):
    form_class = RateForm
    template_name = 'models/rate/create.html'
    success_url = reverse_lazy('currency:rate-list')

    def test_func(self):
        return self.request.user.is_superuser


class RateUpdateView(UserPassesTestMixin, UpdateView):
    form_class = RateForm
    template_name = 'models/rate/update.html'
    success_url = reverse_lazy('currency:rate-list')
    queryset = Rate.objects.all()

    def test_func(self):
        return self.request.user.is_superuser


class RateDeleteView(UserPassesTestMixin, DeleteView):
    queryset = Rate.objects.all()
    template_name = 'models/rate/delete.html'
    success_url = reverse_lazy('currency:rate-list')

    def test_func(self):
        return self.request.user.is_superuser


class ContactUsListView(ModifiedPagesMixin, FilterView):
    paginate_by = 10
    queryset = ContactUs.objects.all()
    template_name = 'models/contactus/list.html'

    filterset_class = ContactUsFilter


class ContactUsDetailsView(DetailView):
    queryset = ContactUs.objects.all()
    template_name = 'models/contactus/details.html'


class ContactUsCreateView(CreateView):
    form_class = ContactUsForm
    template_name = 'models/contactus/create.html'
    success_url = reverse_lazy('currency:contactus-list')

    def form_valid(self, form):

        cleaned_data = form.cleaned_data
        redirect = super().form_valid(form)

        subject = 'Contact Us'
        recipient = settings.DEFAULT_FROM_EMAIL
        message = f"""
                    Reply to email: {cleaned_data['email_from']}
                    Subject: {cleaned_data['subject']}
                    Body: {cleaned_data['message']}
                    """

        send_mail.delay(
            subject=subject,
            from_email=recipient,
            recipient_list=[recipient],
            message=message,
            fail_silently=False
        )

        return redirect


class ContactUsUpdateView(UpdateView):
    form_class = ContactUsForm
    template_name = 'models/contactus/update.html'
    success_url = reverse_lazy('currency:contactus-list')
    queryset = ContactUs.objects.all()


class ContactUsDeleteView(DeleteView):
    queryset = ContactUs.objects.all()
    template_name = 'models/contactus/delete.html'
    success_url = reverse_lazy('currency:contactus-list')


class SourceListView(ModifiedPagesMixin, FilterView):
    paginate_by = 10
    queryset = Source.objects.all()
    template_name = 'models/source/list.html'

    filterset_class = SourceFilter


class SourceDetailsView(DetailView):
    queryset = Source.objects.all()
    template_name = 'models/source/details.html'


class SourceCreateView(CreateView):
    form_class = SourceForm
    template_name = 'models/source/create.html'
    success_url = reverse_lazy('currency:source-list')


class SourceUpdateView(UpdateView):
    form_class = SourceForm
    template_name = 'models/source/update.html'
    success_url = reverse_lazy('currency:source-list')
    queryset = Source.objects.all()


class SourceDeleteView(DeleteView):
    queryset = Source.objects.all()
    template_name = 'models/source/delete.html'
    success_url = reverse_lazy('currency:source-list')


class ProfileView(LoginRequiredMixin, UpdateView):
    template_name = 'registration/profile.html'
    success_url = reverse_lazy('currency:rate-list')
    model = get_user_model()
    queryset = get_user_model().objects.all()
    fields = (
        'first_name',
        'last_name',
    )

    def get_object(self, queryset=None):
        return self.request.user

app/currency/templates/models/rate/all.html
{% extends 'base.html' %}

{% block title %}
    Rates
{% endblock title %}

{% block content %}

<a href="/rate/create/">Create</a><br>

<table>
    <tr>
        <th>Id</th>
        <th>Created</th>
        <th>Currency</th>
        <th>Buy</th>
        <th>Sell</th>
        <th>Source</th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
    {% for rate in rates %}
    <tr>
        <td>{{ rate.id }}</td>
        <td>{{ rate.created }}</td>
        <td>{{ rate.currency }}</td>
        <td>{{ rate.buy }}</td>
        <td>{{ rate.sell }}</td>
        <td>{{ rate.source }}</td>
        <td><a href="/rate/{{ rate.id }}/">Details</a></td>
        <td><a href="/rate/{{ rate.id }}/update/">Update</a></td>
        <td><a href="/rate/{{ rate.id }}/delete/">Delete</a></td>
    </tr>
    {% endfor %}
</table>

{% endblock content %}

app/currency/templates/models/rate/create.html
{% extends 'base.html' %}

{% block title %}
    Create Rate
{% endblock title %}

{% block content %}
    Create Rate Form

    {% include 'includes/forms/create_form.html' %}

{% endblock content %}

app/currency/templates/models/rate/delete.html
{% extends 'base.html' %}

{% block title %}
    Delete Rate
{% endblock title %}

{% block content %}

    Do you really want to delete rate with id {{ rate.id }}
    {% include 'includes/forms/delete_form.html' %}

{% endblock content %}

app/currency/templates/models/rate/details.html
{% extends 'base.html' %}

{% block title %}
    Rate
{% endblock title %}

{% block content %}
    ID: {{ rate.id }}<br>
    Buy: {{ rate.buy }}<br>
    Sale: {{ rate.sale }}<br>
    Source: {{ rate.source }}<br>
    Currency: {{ rate.currency }}<br>
    Created: {{ rate.created }}<br>
    <a href="{% url 'currency:rate-update' rate.id %}">Update</a>
    <a href="{% url 'currency:rate-delete' rate.id %}">Delete</a><br>
{% endblock content %}

app/currency/templates/models/rate/list.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    Rates
{% endblock title %}

{% block content %}

<a href="{% url 'currency:rate-create' %}">Create</a><br>

{% include 'includes/filter_form.html' %}<br>

<table>
    <tr>
        <th>Id</th>
        <th>Created</th>
        <th>Currency</th>
        <th>Buy</th>
        <th>Sale</th>
        <th>Source</th>
        {% if request.user.is_authenticated %}
        <th></th>
        {% endif %}
        {% if request.user.is_superuser %}
        <th></th>
        <th></th>
        {% endif %}
    </tr>
    {% for rate in object_list %}
    <tr>
        <td>{{ rate.id }}</td>
        <td>{{ rate.created }}</td>
        <td>{{ rate.get_currency_display }}</td>
        <td>{{ rate.buy }}</td>
        <td>{{ rate.sale }}</td>
        <td><img src="{{ rate.source.logo_url }}" width="40" height="40">{{ rate.source }}</td>
        {% if request.user.is_authenticated %}
        <td><a href="{% url 'currency:rate-details' rate.id %}">Details</a></td>
        {% endif %}
        {% if request.user.is_superuser %}
        <td><a href="{% url 'currency:rate-update' rate.id %}">Update</a></td>
        <td><a href="{% url 'currency:rate-delete' rate.id %}">Delete</a></td>
        {% endif %}
    </tr>
    {% endfor %}
</table>

{% include 'includes/paginator.html' %}

{% endblock content %}

app/currency/templates/models/rate/update.html
{% extends 'base.html' %}

{% block title %}
    Update Rate
{% endblock title %}

{% block content %}
    Update Rate Form

    {% include 'includes/forms/update_form.html' %}

{% endblock content %}